### PR TITLE
ok cool

### PR DESCRIPTION
**Pull request by PaulProjects**

### CODE REVIEW

**Comment by ChosenChris** [comment]
You bad. My Lisp can do everything your "Taschenrechner" can do, and more!

**Comment by PaulProjects** [comment]
LOL BAD CODE

**Comment by PaulProjects** [comment]
MY CALC VERY POWERFULL

**Comment by PaulProjects** [comment]
IMAGINE BEEING NOT BEEING ABLE TO USE e-Funktion

**Comment by PaulProjects** [comment]
IMAGINE NO GUI

**Comment by PaulProjects** [comment]
HAHAHAHAHAHAH

**Comment by PaulProjects** [comment]
IMAGINE READING THE DOC

**Pull request closed without merging**
